version: "3.9"
services:
  bot:
    image: vulnerable_web
    networks:
      - global_macvlan_net
    volumes:
      - ./bot1_app1/html:/var/www/html:z
    command: ["/bin/bash", "-c", "while true; do curl -s http://192.168.100.1 > /dev/null; echo 'Request sent to 192.168.100.1'; sleep 2; done"]

networks:
  global_macvlan_net:
    external: true
